#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

PLATFORM_PATH := device/amlogic/common

## Android Verified Boot
BOARD_AVB_ENABLE := true

ifneq ($(WITH_AVB),true)
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
endif

BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --prop dovi_hash:3cd93647bdd864b4ae1712d57a7de3153e3ee4a4dfcfae5af8b1b7d999b93c5a

ifeq ($(AVB_CUSTOM_KEY_PATH),)
AVB_CUSTOM_ALGORITHM := SHA256_RSA4096
AVB_CUSTOM_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
endif

BOARD_AVB_ALGORITHM := $(AVB_CUSTOM_ALGORITHM)
BOARD_AVB_KEY_PATH := $(AVB_CUSTOM_KEY_PATH)

BOARD_AVB_ROLLBACK_INDEX := 0

ifneq ($(filter gxm gxl g12a g12b sm1,$(TARGET_AMLOGIC_SOC)),)
BOARD_AVB_RECOVERY_ALGORITHM := $(AVB_CUSTOM_ALGORITHM)
BOARD_AVB_RECOVERY_KEY_PATH := $(AVB_CUSTOM_KEY_PATH)
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 0
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 2
else
BOARD_AVB_VBMETA_SYSTEM := system system_ext system_dlkm
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := $(AVB_CUSTOM_ALGORITHM)
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := $(AVB_CUSTOM_KEY_PATH)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 2
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true
endif

## Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_KERNEL_ARCH := arm64

## Audio
BOARD_USES_ALSA_AUDIO := true

## Dex Pre-Opt
WITH_DEXPREOPT_DEBUG_INFO := false

## Display
ifeq ($(PRODUCT_IS_ATV),true)
TARGET_SCREEN_DENSITY ?= 320
else
TARGET_SCREEN_DENSITY ?= 240
endif

## Kernel
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

BOARD_KERNEL_CMDLINE += androidboot.dtbo_idx=0 hdr_policy=1
ifeq ($(strip $(TARGET_BOOTDEVICE)),usb)
BOARD_KERNEL_CMDLINE += otg_device=0
else ifeq ($(strip $(TARGET_USB_DEFAULT_MODE)),host)
BOARD_KERNEL_CMDLINE += otg_device=0
else
BOARD_KERNEL_CMDLINE += otg_device=1
endif

ifneq ($(filter gxm gxl g12a g12b sm1,$(TARGET_AMLOGIC_SOC)),)
BOARD_BOOT_HEADER_VERSION := 2
BOARD_DTB_OFFSET          := 0x00e88000
BOARD_KERNEL_BASE         := 0x01078000
BOARD_KERNEL_OFFSET       := 0x00008000
BOARD_KERNEL_PAGESIZE     := 2048
BOARD_RAMDISK_OFFSET      := 0xfef10000
BOARD_SECOND_OFFSET       := 0xfee10000
BOARD_TAGS_OFFSET         := 0xfdf10100
BOARD_KERNEL_IMAGE_NAME   := Image.gz
BOARD_RAMDISK_USE_XZ      := true
BOARD_MKBOOTIMG_ARGS      := --kernel_offset $(BOARD_KERNEL_OFFSET) --second_offset $(BOARD_SECOND_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --dtb_offset $(BOARD_DTB_OFFSET) --header_version $(BOARD_BOOT_HEADER_VERSION)
TARGET_BOOTLOADER_IS_2ND  := true
else
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_BASE         := 0x0
BOARD_KERNEL_OFFSET       := 0x2080000
BOARD_KERNEL_PAGESIZE     := 4096
BOARD_KERNEL_IMAGE_NAME   := Image.lz4
BOARD_MKBOOTIMG_ARGS      := --kernel_offset $(BOARD_KERNEL_OFFSET) --header_version $(BOARD_BOOT_HEADER_VERSION)
endif

## Partitions
ifneq ($(filter gxm gxl g12a g12b sm1,$(TARGET_AMLOGIC_SOC)),)
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 25165824
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 838860800
BOARD_DTBIMAGE_PARTITION_SIZE := 262144
else
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 25165824
BOARD_DTBIMAGE_PARTITION_SIZE := 258048
endif

BOARD_DTBOIMG_PARTITION_SIZE := 2097152
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_USES_METADATA_PARTITION := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

ifeq ($(PRODUCT_USE_DYNAMIC_PARTITIONS), true)
include vendor/lineage/config/BoardConfigReservedSize.mk
endif

$(foreach p, $(call to-upper, $(SSI_PARTITIONS)), \
    $(eval BOARD_$(p)IMAGE_FILE_SYSTEM_TYPE := ext4) \
    $(eval TARGET_COPY_OUT_$(p) := $(call to-lower, $(p))))

$(foreach p, $(call to-upper, $(TREBLE_PARTITIONS)), \
    $(eval BOARD_$(p)IMAGE_FILE_SYSTEM_TYPE := erofs) \
    $(eval TARGET_COPY_OUT_$(p) := $(call to-lower, $(p))))

## Platform
TARGET_BOARD_PLATFORM := amlogic

## Properties
TARGET_SYSTEM_EXT_PROP += $(PLATFORM_PATH)/system_ext.prop
TARGET_PRODUCT_PROP += $(PLATFORM_PATH)/product.prop
TARGET_VENDOR_PROP += $(PLATFORM_PATH)/vendor.prop

## Recovery
TARGET_RECOVERY_DENSITY := 200dpi
TARGET_RECOVERY_PIXEL_FORMAT := BGRA_8888

## SELinux
include device/lineage/sepolicy/libion/sepolicy.mk
include device/amlogic/sepolicy/sepolicy.mk

## Wi-Fi
ifneq ($(BOARD_HAVE_WIFI),false)
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true
WPA_SUPPLICANT_VERSION := VER_0_8_X
endif
